// D3.js Visualization Renderer
// This module renders the visualizations generated by the visualization_generator.js module

/**
 * SiteMapRenderer class
 * Renders a hierarchical site map using D3.js
 */
class SiteMapRenderer {
  /**
   * Constructor for the SiteMapRenderer
   * @param {string} containerId - The ID of the container element
   * @param {Object} options - Rendering options
   */
  constructor(containerId, options = {}) {
    this.containerId = containerId;
    this.options = Object.assign({
      width: 800,
      height: 600,
      nodeRadius: 30,
      nodeColor: '#4f46e5',
      linkColor: '#9ca3af',
      textColor: '#1f2937',
      margin: { top: 50, right: 50, bottom: 50, left: 50 }
    }, options);
    
    this.svg = null;
    this.treeLayout = null;
  }
  
  /**
   * Initialize the D3.js tree layout
   * @private
   */
  _initializeLayout() {
    const { width, height, margin } = this.options;
    
    // Create SVG element
    this.svg = d3.select(`#${this.containerId}`)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`);
    
    // Create tree layout
    this.treeLayout = d3.tree()
      .size([width - margin.left - margin.right, height - margin.top - margin.bottom]);
  }
  
  /**
   * Render the site map
   * @param {Object} siteMapData - The site map data in D3.js format
   */
  render(siteMapData) {
    if (!this.svg) {
      this._initializeLayout();
    }
    
    // Convert data to D3 hierarchy
    const root = d3.hierarchy(siteMapData);
    
    // Apply the tree layout
    const treeData = this.treeLayout(root);
    
    // Add links
    const links = this.svg.selectAll('.link')
      .data(treeData.links())
      .enter()
      .append('path')
      .attr('class', 'link')
      .attr('d', d3.linkVertical()
        .x(d => d.x)
        .y(d => d.y))
      .attr('fill', 'none')
      .attr('stroke', this.options.linkColor)
      .attr('stroke-width', 1.5);
    
    // Add nodes
    const nodes = this.svg.selectAll('.node')
      .data(treeData.descendants())
      .enter()
      .append('g')
      .attr('class', 'node')
      .attr('transform', d => `translate(${d.x},${d.y})`);
    
    // Add circles for nodes
    nodes.append('circle')
      .attr('r', this.options.nodeRadius)
      .attr('fill', this.options.nodeColor)
      .attr('stroke', '#fff')
      .attr('stroke-width', 2);
    
    // Add text labels
    nodes.append('text')
      .attr('dy', '0.35em')
      .attr('text-anchor', 'middle')
      .text(d => d.data.name)
      .attr('fill', '#fff')
      .style('font-size', '12px')
      .style('font-weight', 'bold');
    
    // Add interaction
    nodes.on('mouseover', function() {
      d3.select(this).select('circle')
        .attr('r', d => d.options.nodeRadius * 1.2);
    })
    .on('mouseout', function() {
      d3.select(this).select('circle')
        .attr('r', d => d.options.nodeRadius);
    })
    .on('click', function(event, d) {
      // Handle click event
      console.log('Node clicked:', d.data.name);
    });
  }
  
  /**
   * Update the site map with new data
   * @param {Object} siteMapData - The new site map data
   */
  update(siteMapData) {
    // Clear existing visualization
    d3.select(`#${this.containerId}`).selectAll('*').remove();
    this.svg = null;
    
    // Render with new data
    this.render(siteMapData);
  }
}

/**
 * ComponentRelationshipRenderer class
 * Renders a force-directed graph of component relationships using D3.js
 */
class ComponentRelationshipRenderer {
  /**
   * Constructor for the ComponentRelationshipRenderer
   * @param {string} containerId - The ID of the container element
   * @param {Object} options - Rendering options
   */
  constructor(containerId, options = {}) {
    this.containerId = containerId;
    this.options = Object.assign({
      width: 800,
      height: 600,
      nodeRadius: 20,
      linkDistance: 100,
      charge: -300,
      nodeColors: {
        'Feature': '#4f46e5',
        'Frontend': '#10b981',
        'Backend': '#ef4444',
        'Database': '#f59e0b',
        'Integration': '#3b82f6',
        'default': '#6b7280'
      },
      linkColors: {
        'communicates-with': '#9ca3af',
        'implemented-by': '#818cf8',
        'depends-on': '#ef4444',
        'default': '#d1d5db'
      }
    }, options);
    
    this.svg = null;
    this.simulation = null;
  }
  
  /**
   * Initialize the D3.js force simulation
   * @private
   */
  _initializeLayout() {
    const { width, height } = this.options;
    
    // Create SVG element
    this.svg = d3.select(`#${this.containerId}`)
      .append('svg')
      .attr('width', width)
      .attr('height', height);
    
    // Create force simulation
    this.simulation = d3.forceSimulation()
      .force('link', d3.forceLink().id(d => d.id).distance(this.options.linkDistance))
      .force('charge', d3.forceManyBody().strength(this.options.charge))
      .force('center', d3.forceCenter(width / 2, height / 2))
      .force('collision', d3.forceCollide().radius(this.options.nodeRadius * 1.5));
  }
  
  /**
   * Get node color based on type
   * @private
   * @param {string} type - The node type
   * @returns {string} - The color code
   */
  _getNodeColor(type) {
    return this.options.nodeColors[type] || this.options.nodeColors.default;
  }
  
  /**
   * Get link color based on type
   * @private
   * @param {string} type - The link type
   * @returns {string} - The color code
   */
  _getLinkColor(type) {
    return this.options.linkColors[type] || this.options.linkColors.default;
  }
  
  /**
   * Render the component relationships
   * @param {Object} relationshipData - The relationship data in D3.js format
   */
  render(relationshipData) {
    if (!this.svg) {
      this._initializeLayout();
    }
    
    const { nodes, links } = relationshipData;
    
    // Create links
    const link = this.svg.append('g')
      .attr('class', 'links')
      .selectAll('line')
      .data(links)
      .enter()
      .append('line')
      .attr('stroke', d => this._getLinkColor(d.type))
      .attr('stroke-width', 1.5);
    
    // Create nodes
    const node = this.svg.append('g')
      .attr('class', 'nodes')
      .selectAll('g')
      .data(nodes)
      .enter()
      .append('g')
      .call(d3.drag()
        .on('start', this._dragStarted.bind(this))
        .on('drag', this._dragged.bind(this))
        .on('end', this._dragEnded.bind(this)));
    
    // Add circles for nodes
    node.append('circle')
      .attr('r', this.options.nodeRadius)
      .attr('fill', d => this._getNodeColor(d.type))
      .attr('stroke', '#fff')
      .attr('stroke-width', 2);
    
    // Add text labels
    node.append('text')
      .attr('dy', '0.35em')
      .attr('text-anchor', 'middle')
      .text(d => d.name)
      .attr('fill', '#fff')
      .style('font-size', '10px')
      .style('font-weight', 'bold');
    
    // Add tooltips
    node.append('title')
      .text(d => `${d.name} (${d.type})`);
    
    // Update simulation
    this.simulation
      .nodes(nodes)
      .on('tick', () => {
        link
          .attr('x1', d => d.source.x)
          .attr('y1', d => d.source.y)
          .attr('x2', d => d.target.x)
          .attr('y2', d => d.target.y);
        
        node
          .attr('transform', d => `translate(${d.x},${d.y})`);
      });
    
    this.simulation.force('link')
      .links(links);
  }
  
  /**
   * Handle drag start event
   * @private
   * @param {Event} event - The drag event
   * @param {Object} d - The node data
   */
  _dragStarted(event, d) {
    if (!event.active) this.simulation.alphaTarget(0.3).restart();
    d.fx = d.x;
    d.fy = d.y;
  }
  
  /**
   * Handle drag event
   * @private
   * @param {Event} event - The drag event
   * @param {Object} d - The node data
   */
  _dragged(event, d) {
    d.fx = event.x;
    d.fy = event.y;
  }
  
  /**
   * Handle drag end event
   * @private
   * @param {Event} event - The drag event
   * @param {Object} d - The node data
   */
  _dragEnded(event, d) {
    if (!event.active) this.simulation.alphaTarget(0);
    d.fx = null;
    d.fy = null;
  }
  
  /**
   * Update the component relationships with new data
   * @param {Object} relationshipData - The new relationship data
   */
  update(relationshipData) {
    // Clear existing visualization
    d3.select(`#${this.containerId}`).selectAll('*').remove();
    this.svg = null;
    this.simulation = null;
    
    // Render with new data
    this.render(relationshipData);
  }
}

/**
 * UserFlowRenderer class
 * Renders a user flow diagram using D3.js
 */
class UserFlowRenderer {
  /**
   * Constructor for the UserFlowRenderer
   * @param {string} containerId - The ID of the container element
   * @param {Object} options - Rendering options
   */
  constructor(containerId, options = {}) {
    this.containerId = containerId;
    this.options = Object.assign({
      width: 800,
      height: 600,
      nodeWidth: 200,
      nodeHeight: 80,
      nodeColor: '#4f46e5',
      linkColor: '#9ca3af',
      textColor: '#fff',
      margin: { top: 50, right: 50, bottom: 50, left: 50 }
    }, options);
    
    this.svg = null;
  }
  
  /**
   * Initialize the D3.js layout
   * @private
   */
  _initializeLayout() {
    const { width, height, margin } = this.options;
    
    // Create SVG element
    this.svg = d3.select(`#${this.containerId}`)
      .append('svg')
      .attr('width', width)
      .attr('height', height)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`);
  }
  
  /**
   * Render the user flow
   * @param {Object} userFlowData - The user flow data in D3.js format
   */
  render(userFlowData) {
    if (!this.svg) {
      this._initializeLayout();
    }
    
    const { nodes, links } = userFlowData;
    const { nodeWidth, nodeHeight, nodeColor, linkColor, textColor } = this.options;
    
    // Position nodes in a vertical flow
    const nodePositions = {};
    nodes.forEach((node, i) => {
      nodePositions[node.id] = {
        x: (this.options.width - this.options.margin.left - this.options.margin.right - nodeWidth) / 2,
        y: i * (nodeHeight + 50) + 20
      };
    });
    
    // Create links
    const linkGenerator = d3.linkVertical()
      .x(d => d.x + nodeWidth / 2)
      .y(d => d.y);
    
    const link = this.svg.selectAll('.link')
      .data(links)
      .enter()
      .append('path')
      .attr('class', 'link')
      .attr('d', d => {
        const sourcePos = nodePositions[d.source];
        const targetPos = nodePositions[d.target];
        return linkGenerator({
          source: { x: sourcePos.x, y: sourcePos.y + nodeHeight },
          target: { x: targetPos.x, y: targetPos.y }
        });
      })
      .attr('fill', 'none')
      .attr('stroke', linkColor)
      .attr('stroke-width', 2)
      .attr('marker-end', 'url(#arrowhead)');
    
    // Add arrowhead marker
    this.svg.append('defs').append('marker')
      .attr('id', 'arrowhead')
      .attr('viewBox', '0 -5 10 10')
      .attr('refX', 8)
      .attr('refY', 0)
      .attr('orient', 'auto')
      .attr('markerWidth', 6)
      .attr('markerHeight', 6)
      .append('path')
      .attr('d', 'M0,-5L10,0L0,5')
      .attr('fill', linkColor);
    
    // Create nodes
    const node = this.svg.selectAll('.node')
      .data(nodes)
      .enter()
      .append('g')
      .attr('class', 'node')
      .attr('transform', d => {
        const pos = nodePositions[d.id];
        return `translate(${pos.x},${pos.y})`;
      });
    
    // Add rectangles for nodes
    node.append('rect')
      .attr('width', nodeWidth)
      .attr('height', nodeHeight)
      .attr('rx', 5)
      .attr('ry', 5)
      .attr('fill', nodeColor)
      .attr('stroke', '#fff')
      .attr('stroke-width', 2);
    
    // Add text labels
    node.append('text')
      .attr('x', nodeWidth / 2)
      .attr('y', 25)
      .attr('text-anchor', 'middle')
      .text(d => d.name)
      .attr('fill', textColor)
      .style('font-size', '14px')
      .style('font-weight', 'bold');
    
    // Add description text
    node.append('text')
      .attr('x', nodeWidth / 2)
      .attr('y', 45)
      .attr('text-anchor', 'middle')
      .text(d => {
        // Truncate description if too long
        const maxLength = 25;
        return d.description.length > maxLength
          ? d.description.substring(0, maxLength) + '...'
          : d.description;
      })
      .attr('fill', textColor)
      .style('font-size', '10px');
    
    // Add interaction
    node.on('mouseover', function() {
      d3.select(this).select('rect')
        .attr('fill', d3.color(nodeColor).brighter(0.3));
    })
    .on('mouseout', function() {
      d3.select(this).select('rect')
        .attr('fill', nodeColor);
    })
    .on('click', function(event, d) {
      // Handle click event
      console.log('Node clicked:', d.name);
    });
  }
  
  /**
   * Update the user flow with new data
   * @param {Object} userFlowData - The new user flow data
   */
  update(userFlowData) {
    // Clear existing visualization
    d3.select(`#${this.containerId}`).selectAll('*').remove();
    this.svg = null;
    
    // Render with new data
    this.render(userFlowData);
  }
}

/**
 * VisualizationRenderer class
 * Main class for rendering all visualizations
 */
class VisualizationRenderer {
  /**
   * Constructor for the VisualizationRenderer
   * @param {Object} options - Rendering options
   */
  constructor(options = {}) {
    this.options = options;
    this.renderers = {};
  }
  
  /**
   * Initialize all renderers
   * @param {Object} containerIds - Object mapping visualization types to container IDs
   */
  initialize(containerIds) {
    if (containerIds.siteMap) {
      this.renderers.siteMap = new SiteMapRenderer(
        containerIds.siteMap,
        this.options.siteMap
      );
    }
    
    if (containerIds.relationships) {
      this.renderers.relationships = new ComponentRelationshipRenderer(
        containerIds.relationships,
        this.options.relationships
      );
    }
    
    if (containerIds.userFlow) {
      this.renderers.userFlow = new UserFlowRenderer(
        containerIds.userFlow,
        this.options.userFlow
      );
    }
  }
  
  /**
   * Render all visualizations
   * @param {Object} visualizationData - The visualization data
   */
  renderAll(visualizationData) {
    if (this.renderers.siteMap && visualizationData.siteMapD3) {
      this.renderers.siteMap.render(visualizationData.siteMapD3);
    }
    
    if (this.renderers.relationships && visualizationData.relationshipsD3) {
      this.renderers.relationships.render(visualizationData.relationshipsD3);
    }
    
    if (this.renderers.userFlow && visualizationData.userFlowD3) {
      this.renderers.userFlow.render(visualizationData.userFlowD3);
    }
  }
  
  /**
   * Update all visualizations with new data
   * @param {Object} visualizationData - The new visualization data
   */
  updateAll(visualizationData) {
    if (this.renderers.siteMap && visualizationData.siteMapD3) {
      this.renderers.siteMap.update(visualizationData.siteMapD3);
    }
    
    if (this.renderers.relationships && visualizationData.relationshipsD3) {
      this.renderers.relationships.update(visualizationData.relationshipsD3);
    }
    
    if (this.renderers.userFlow && visualizationData.userFlowD3) {
      this.renderers.userFlow.update(visualizationData.userFlowD3);
    }
  }
}

// Export the classes
module.exports = {
  SiteMapRenderer,
  ComponentRelationshipRenderer,
  UserFlowRenderer,
  VisualizationRenderer
};
