"""
Visualization Generator Module

This module creates data structures for interactive visualizations based on 
the documentation generated by the AI documentation generator.
It includes site maps, component relationships, and user flows.
"""

class SiteMapGenerator:
    """
    Generates a hierarchical site map based on the content structure
    """
    
    @staticmethod
    def generate_site_map(documentation):
        """
        Generates a hierarchical site map based on the content structure
        
        Args:
            documentation: The documentation object from the AI generator
            
        Returns:
            A hierarchical site map structure
        """
        content_structure = documentation.get('content_structure', [])
        features = documentation.get('features', [])
        
        # Create root node (home page)
        site_map = {
            "id": 'home',
            "name": 'Home Page',
            "type": 'page',
            "children": []
        }
        
        # Add main sections based on content structure
        if content_structure and isinstance(content_structure, list):
            for index, section in enumerate(content_structure):
                section_node = {
                    "id": f"section-{index}",
                    "name": section.get('section_name', f"Section {index}"),
                    "type": 'page',
                    "children": []
                }
                
                # Add subsections or content elements if available
                if 'content_elements' in section and isinstance(section['content_elements'], list):
                    for elem_index, element in enumerate(section['content_elements']):
                        section_node['children'].append({
                            "id": f"element-{index}-{elem_index}",
                            "name": element,
                            "type": 'component',
                            "children": []
                        })
                
                site_map['children'].append(section_node)
        
        # Add feature-specific pages
        if features and isinstance(features, list):
            features_node = {
                "id": 'features',
                "name": 'Features',
                "type": 'page',
                "children": []
            }
            
            for index, feature in enumerate(features):
                features_node['children'].append({
                    "id": f"feature-{index}",
                    "name": feature.get('name', f"Feature {index}"),
                    "type": 'page',
                    "children": []
                })
            
            site_map['children'].append(features_node)
        
        return site_map
    
    @staticmethod
    def convert_to_d3_format(site_map):
        """
        Converts the site map to D3.js compatible format
        
        Args:
            site_map: The site map object
            
        Returns:
            D3.js compatible hierarchy
        """
        return {
            "name": site_map.get('name', ''),
            "children": [
                {
                    "name": child.get('name', ''),
                    "children": [
                        {"name": grandchild.get('name', '')} 
                        for grandchild in child.get('children', [])
                    ]
                } 
                for child in site_map.get('children', [])
            ]
        }


class ComponentRelationshipGenerator:
    """
    Generates component relationship diagrams based on the documentation
    """
    
    @staticmethod
    def generate_component_relationships(documentation):
        """
        Generates component relationship diagrams based on the documentation
        
        Args:
            documentation: The documentation object from the AI generator
            
        Returns:
            Component relationships structure
        """
        features = documentation.get('features', [])
        tech_stack = documentation.get('tech_stack', [])
        
        # Create nodes for each component
        nodes = []
        links = []
        
        # Add feature components
        if features and isinstance(features, list):
            for index, feature in enumerate(features):
                nodes.append({
                    "id": f"feature-{index}",
                    "name": feature.get('name', f"Feature {index}"),
                    "type": 'Feature',
                    "description": feature.get('description', '')
                })
        
        # Add tech stack components
        if tech_stack and isinstance(tech_stack, list):
            for index, tech in enumerate(tech_stack):
                nodes.append({
                    "id": f"tech-{index}",
                    "name": tech.get('name', f"Technology {index}"),
                    "type": tech.get('category', 'Technology'),
                    "description": tech.get('description', '')
                })
                
                # Create links between related technologies
                if tech.get('category') == 'Frontend':
                    # Connect frontend to backend
                    backend_techs = [t for t in tech_stack if t.get('category') == 'Backend']
                    for backend_tech in backend_techs:
                        backend_index = tech_stack.index(backend_tech)
                        links.append({
                            "source": f"tech-{index}",
                            "target": f"tech-{backend_index}",
                            "type": 'communicates-with'
                        })
        
        # Connect features to relevant technologies
        if features and tech_stack:
            for feature_index, feature in enumerate(features):
                # Simplified logic to determine relevant technologies
                feature_details = feature.get('details', [])
                feature_desc = feature.get('description', '').lower()
                
                for tech_index, tech in enumerate(tech_stack):
                    tech_name = tech.get('name', '').lower()
                    tech_desc = tech.get('description', '').lower()
                    
                    # Check if tech is relevant to this feature
                    is_relevant = False
                    
                    # Check if tech name appears in feature description
                    if tech_name in feature_desc:
                        is_relevant = True
                    
                    # Check if tech name appears in feature details
                    if not is_relevant:
                        for detail in feature_details:
                            if isinstance(detail, str) and tech_name in detail.lower():
                                is_relevant = True
                                break
                    
                    if is_relevant:
                        links.append({
                            "source": f"feature-{feature_index}",
                            "target": f"tech-{tech_index}",
                            "type": 'implemented-by'
                        })
        
        return {"nodes": nodes, "links": links}
    
    @staticmethod
    def convert_to_d3_format(relationships):
        """
        Converts the component relationships to D3.js compatible format
        
        Args:
            relationships: The component relationships object
            
        Returns:
            D3.js compatible network graph
        """
        return {
            "nodes": [
                {
                    "id": node.get('id', ''),
                    "name": node.get('name', ''),
                    "type": node.get('type', '')
                } for node in relationships.get('nodes', [])
            ],
            "links": [
                {
                    "source": link.get('source', ''),
                    "target": link.get('target', ''),
                    "type": link.get('type', '')
                } for link in relationships.get('links', [])
            ]
        }


class UserFlowGenerator:
    """
    Generates user flow diagrams based on the documentation
    """
    
    @staticmethod
    def generate_user_flows(documentation):
        """
        Generates user flow diagrams based on the documentation
        
        Args:
            documentation: The documentation object from the AI generator
            
        Returns:
            User flow structure
        """
        features = documentation.get('features', [])
        content_structure = documentation.get('content_structure', [])
        
        # Create a default user flow
        user_flow = {
            "name": 'Primary User Flow',
            "steps": []
        }
        
        # Add landing on home page as first step
        user_flow['steps'].append({
            "id": 'step-1',
            "name": 'User Lands on Home Page',
            "description": 'User arrives at the site and views the home page content.',
            "components": ['Header', 'Hero Section', 'Featured Content']
        })
        
        # Add steps based on content structure
        if content_structure and isinstance(content_structure, list):
            for index, section in enumerate(content_structure):
                section_name = section.get('section_name', '').lower()
                if section_name != 'home' and section_name != 'footer':
                    user_flow['steps'].append({
                        "id": f"step-{index + 2}",
                        "name": f"User Explores {section.get('section_name', f'Section {index}')}",
                        "description": f"User navigates to and interacts with the {section.get('section_name', f'Section {index}')} section.",
                        "components": ['Header', section.get('section_name', f'Section {index}'), 'Footer']
                    })
        
        # Add feature-specific steps
        if features and isinstance(features, list):
            # Find high-priority features
            high_priority_features = [f for f in features if f.get('priority', '').lower() == 'high']
            
            for index, feature in enumerate(high_priority_features):
                user_flow['steps'].append({
                    "id": f"step-feature-{index}",
                    "name": f"User Interacts with {feature.get('name', f'Feature {index}')}",
                    "description": feature.get('description', ''),
                    "components": [feature.get('name', f'Feature {index}')]
                })
        
        # Add final conversion step
        user_flow['steps'].append({
            "id": "step-final",
            "name": 'User Completes Primary Goal',
            "description": 'User completes the primary goal of the site (e.g., submits a form, makes a purchase).',
            "components": ['Conversion Component', 'Confirmation Page']
        })
        
        return user_flow
    
    @staticmethod
    def convert_to_d3_format(user_flow):
        """
        Converts the user flow to D3.js compatible format
        
        Args:
            user_flow: The user flow object
            
        Returns:
            D3.js compatible flow diagram
        """
        steps = user_flow.get('steps', [])
        return {
            "name": user_flow.get('name', ''),
            "nodes": [
                {
                    "id": step.get('id', ''),
                    "name": step.get('name', ''),
                    "description": step.get('description', '')
                } for step in steps
            ],
            "links": [
                {
                    "source": steps[i].get('id', ''),
                    "target": steps[i+1].get('id', '')
                } for i in range(len(steps)-1)
            ]
        }


class VisualizationGenerator:
    """
    Main class for generating all visualizations
    """
    
    @staticmethod
    def generateVisualizations(documentation):
        """
        Generates all visualizations based on the documentation
        
        Args:
            documentation: The documentation object from the AI generator
            
        Returns:
            All visualizations
        """
        # Generate site map
        site_map = SiteMapGenerator.generate_site_map(documentation)
        site_map_d3 = SiteMapGenerator.convert_to_d3_format(site_map)
        
        # Generate component relationships
        component_relationships = ComponentRelationshipGenerator.generate_component_relationships(documentation)
        relationships_d3 = ComponentRelationshipGenerator.convert_to_d3_format(component_relationships)
        
        # Generate user flows
        user_flow = UserFlowGenerator.generate_user_flows(documentation)
        user_flow_d3 = UserFlowGenerator.convert_to_d3_format(user_flow)
        
        return {
            "siteMap": site_map,
            "siteMapD3": site_map_d3,
            "componentRelationships": component_relationships,
            "relationshipsD3": relationships_d3,
            "userFlow": user_flow,
            "userFlowD3": user_flow_d3
        }