"""
Export Engine Module

This module handles the export of documentation to various formats including PDF and DOCX.
It takes the structured documentation generated by the AI and creates well-formatted documents.
"""

import os
import json
import pdfkit
import tempfile
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

class ExportEngine:
    """
    Handles the export of documentation to various formats.
    """
    
    def __init__(self, config=None):
        """
        Initialize the ExportEngine.
        
        Args:
            config: Configuration options for the export engine
        """
        self.config = config or {}
        self.pdf_options = {
            'page-size': 'A4',
            'margin-top': '20mm',
            'margin-right': '20mm',
            'margin-bottom': '20mm',
            'margin-left': '20mm',
            'encoding': 'UTF-8',
            'no-outline': None,
            'enable-local-file-access': None
        }
    
    def _generate_html(self, documentation):
        """
        Generate HTML from the documentation.
        
        Args:
            documentation: The documentation object
            
        Returns:
            HTML string representation of the documentation
        """
        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{documentation.get('project_summary', {}).get('title', 'Project Documentation')}</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{
                    color: #4f46e5;
                    border-bottom: 2px solid #4f46e5;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #4f46e5;
                    margin-top: 30px;
                }}
                h3 {{
                    color: #6b7280;
                    margin-top: 20px;
                }}
                .section {{
                    margin-bottom: 30px;
                }}
                .feature {{
                    background-color: #f9fafb;
                    border-left: 4px solid #4f46e5;
                    padding: 15px;
                    margin-bottom: 15px;
                }}
                .tech-item {{
                    background-color: #f9fafb;
                    border-left: 4px solid #10b981;
                    padding: 15px;
                    margin-bottom: 15px;
                }}
                .content-section {{
                    background-color: #f9fafb;
                    border-left: 4px solid #3b82f6;
                    padding: 15px;
                    margin-bottom: 15px;
                }}
                .implementation-step {{
                    background-color: #f9fafb;
                    border-left: 4px solid #f59e0b;
                    padding: 15px;
                    margin-bottom: 15px;
                }}
                ul, ol {{
                    padding-left: 20px;
                }}
                .footer {{
                    margin-top: 50px;
                    text-align: center;
                    color: #6b7280;
                    font-size: 0.8em;
                }}
            </style>
        </head>
        <body>
            <h1>{documentation.get('project_summary', {}).get('title', 'Project Documentation')}</h1>
            
            <div class="section">
                <h2>Project Summary</h2>
                <p>{documentation.get('project_summary', {}).get('description', '')}</p>
                
                <h3>Objectives</h3>
                <ul>
        """
        
        # Add objectives
        for objective in documentation.get('project_summary', {}).get('objectives', []):
            html += f"<li>{objective}</li>\n"
        
        html += f"""
                </ul>
                
                <h3>Scope</h3>
                <p>{documentation.get('project_summary', {}).get('scope', '')}</p>
            </div>
            
            <div class="section">
                <h2>Target Audience</h2>
                <p><strong>Primary Audience:</strong> {documentation.get('target_audience', {}).get('primary_audience', '')}</p>
        """
        
        # Add secondary audience if available
        secondary_audience = documentation.get('target_audience', {}).get('secondary_audience')
        if secondary_audience:
            html += f"<p><strong>Secondary Audience:</strong> {secondary_audience}</p>\n"
        
        html += """
                <h3>User Characteristics</h3>
                <ul>
        """
        
        # Add user characteristics
        for characteristic in documentation.get('target_audience', {}).get('user_characteristics', []):
            html += f"<li>{characteristic}</li>\n"
        
        html += """
                </ul>
                
                <h3>User Needs</h3>
                <ul>
        """
        
        # Add user needs
        for need in documentation.get('target_audience', {}).get('user_needs', []):
            html += f"<li>{need}</li>\n"
        
        html += """
                </ul>
            </div>
            
            <div class="section">
                <h2>Features</h2>
        """
        
        # Add features
        for feature in documentation.get('features', []):
            html += f"""
                <div class="feature">
                    <h3>{feature.get('name', '')}</h3>
                    <p>{feature.get('description', '')}</p>
                    <p><strong>Priority:</strong> {feature.get('priority', '')}</p>
                    <h4>Details</h4>
                    <ul>
            """
            
            for detail in feature.get('details', []):
                html += f"<li>{detail}</li>\n"
            
            html += """
                    </ul>
                </div>
            """
        
        html += """
            </div>
            
            <div class="section">
                <h2>Technology Stack</h2>
        """
        
        # Add tech stack items
        for tech in documentation.get('tech_stack', []):
            html += f"""
                <div class="tech-item">
                    <h3>{tech.get('name', '')}</h3>
                    <p><strong>Category:</strong> {tech.get('category', '')}</p>
                    <p>{tech.get('description', '')}</p>
                    <h4>Benefits</h4>
                    <ul>
            """
            
            for benefit in tech.get('benefits', []):
                html += f"<li>{benefit}</li>\n"
            
            html += """
                    </ul>
            """
            
            # Add alternatives if available
            alternatives = tech.get('alternatives')
            if alternatives and len(alternatives) > 0:
                html += """
                    <h4>Alternatives</h4>
                    <ul>
                """
                
                for alternative in alternatives:
                    html += f"<li>{alternative}</li>\n"
                
                html += """
                    </ul>
                """
            
            html += """
                </div>
            """
        
        html += """
            </div>
            
            <div class="section">
                <h2>Content Structure</h2>
        """
        
        # Add content structure
        for section in documentation.get('content_structure', []):
            html += f"""
                <div class="content-section">
                    <h3>{section.get('section_name', '')}</h3>
                    <p>{section.get('description', '')}</p>
                    <h4>Content Elements</h4>
                    <ul>
            """
            
            for element in section.get('content_elements', []):
                html += f"<li>{element}</li>\n"
            
            html += """
                    </ul>
            """
            
            # Add design considerations if available
            considerations = section.get('design_considerations')
            if considerations and len(considerations) > 0:
                html += """
                    <h4>Design Considerations</h4>
                    <ul>
                """
                
                for consideration in considerations:
                    html += f"<li>{consideration}</li>\n"
                
                html += """
                    </ul>
                """
            
            html += """
                </div>
            """
        
        html += """
            </div>
            
            <div class="section">
                <h2>Implementation Plan</h2>
        """
        
        # Add implementation steps
        for step in sorted(documentation.get('implementation_plan', []), key=lambda x: x.get('step_number', 0)):
            html += f"""
                <div class="implementation-step">
                    <h3>Step {step.get('step_number', '')}: {step.get('title', '')}</h3>
                    <p>{step.get('description', '')}</p>
            """
            
            # Add estimated time if available
            estimated_time = step.get('estimated_time')
            if estimated_time:
                html += f"<p><strong>Estimated Time:</strong> {estimated_time}</p>\n"
            
            # Add dependencies if available
            dependencies = step.get('dependencies')
            if dependencies and len(dependencies) > 0:
                html += """
                    <h4>Dependencies</h4>
                    <ul>
                """
                
                for dependency in dependencies:
                    html += f"<li>Step {dependency}</li>\n"
                
                html += """
                    </ul>
                """
            
            html += """
                </div>
            """
        
        html += """
            </div>
            
            <div class="section">
                <h2>Deployment Strategy</h2>
                <p><strong>Hosting Recommendation:</strong> {0}</p>
                
                <h3>Deployment Steps</h3>
                <ol>
        """.format(documentation.get('deployment_strategy', {}).get('hosting_recommendation', ''))
        
        # Add deployment steps
        for step in documentation.get('deployment_strategy', {}).get('deployment_steps', []):
            html += f"<li>{step}</li>\n"
        
        html += """
                </ol>
                
                <h3>Scaling Considerations</h3>
                <ul>
        """
        
        # Add scaling considerations
        for consideration in documentation.get('deployment_strategy', {}).get('scaling_considerations', []):
            html += f"<li>{consideration}</li>\n"
        
        html += """
                </ul>
        """
        
        # Add maintenance plan if available
        maintenance_plan = documentation.get('deployment_strategy', {}).get('maintenance_plan')
        if maintenance_plan:
            html += f"""
                <h3>Maintenance Plan</h3>
                <p>{maintenance_plan}</p>
            """
        
        html += """
            </div>
            
            <div class="footer">
                <p>Generated by DevBridge - AI-Powered Pre-Development Automation Platform</p>
                <p>© 2025 DevBridge</p>
            </div>
        </body>
        </html>
        """
        
        return html
    
    def export_to_simple_pdf(self, documentation, output_path):
            try:
                from reportlab.lib.pagesizes import letter
                from reportlab.lib import colors
                from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListItem, ListFlowable
                from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
                
                # Create document
                doc = SimpleDocTemplate(output_path, pagesize=letter)
                styles = getSampleStyleSheet()
                
                # Create custom styles
                styles.add(ParagraphStyle(name='Title', 
                                          fontName='Helvetica-Bold', 
                                          fontSize=18, 
                                          textColor=colors.HexColor('#4f46e5'),
                                          spaceAfter=12))
                
                styles.add(ParagraphStyle(name='Heading1', 
                                          fontName='Helvetica-Bold', 
                                          fontSize=16, 
                                          textColor=colors.HexColor('#4f46e5'),
                                          spaceAfter=8,
                                          spaceBefore=16))
                
                styles.add(ParagraphStyle(name='Heading2', 
                                          fontName='Helvetica-Bold', 
                                          fontSize=14, 
                                          textColor=colors.HexColor('#6b7280'),
                                          spaceAfter=6,
                                          spaceBefore=12))
                
                # Create content elements
                elements = []
                
                # Add title
                title = documentation.get('project_summary', {}).get('title', 'Project Documentation')
                elements.append(Paragraph(title, styles['Title']))
                elements.append(Spacer(1, 12))
                
                # Add project summary
                elements.append(Paragraph("Project Summary", styles['Heading1']))
                description = documentation.get('project_summary', {}).get('description', '')
                elements.append(Paragraph(description, styles['Normal']))
                
                # Add objectives
                elements.append(Paragraph("Objectives", styles['Heading2']))
                objectives = documentation.get('project_summary', {}).get('objectives', [])
                if objectives:
                    items = []
                    for objective in objectives:
                        items.append(ListItem(Paragraph(objective, styles['Normal'])))
                    elements.append(ListFlowable(items, bulletType='bullet', start='•'))
                
                # Add scope
                scope = documentation.get('project_summary', {}).get('scope', '')
                if scope:
                    elements.append(Paragraph("Scope", styles['Heading2']))
                    elements.append(Paragraph(scope, styles['Normal']))
                
                # Add target audience
                elements.append(Paragraph("Target Audience", styles['Heading1']))
                primary_audience = documentation.get('target_audience', {}).get('primary_audience', '')
                if primary_audience:
                    elements.append(Paragraph(f"Primary Audience: {primary_audience}", styles['Normal']))
                
                secondary_audience = documentation.get('target_audience', {}).get('secondary_audience', '')
                if secondary_audience:
                    elements.append(Paragraph(f"Secondary Audience: {secondary_audience}", styles['Normal']))
                
                # Add user characteristics
                user_characteristics = documentation.get('target_audience', {}).get('user_characteristics', [])
                if user_characteristics:
                    elements.append(Paragraph("User Characteristics:", styles['Heading2']))
                    items = []
                    for characteristic in user_characteristics:
                        items.append(ListItem(Paragraph(characteristic, styles['Normal'])))
                    elements.append(ListFlowable(items, bulletType='bullet', start='•'))
                
                # Add user needs
                user_needs = documentation.get('target_audience', {}).get('user_needs', [])
                if user_needs:
                    elements.append(Paragraph("User Needs:", styles['Heading2']))
                    items = []
                    for need in user_needs:
                        items.append(ListItem(Paragraph(need, styles['Normal'])))
                    elements.append(ListFlowable(items, bulletType='bullet', start='•'))
                
                # Add features
                elements.append(Paragraph("Features", styles['Heading1']))
                features = documentation.get('features', [])
                for feature in features:
                    elements.append(Paragraph(feature.get('name', ''), styles['Heading2']))
                    elements.append(Paragraph(feature.get('description', ''), styles['Normal']))
                    elements.append(Paragraph(f"Priority: {feature.get('priority', '')}", styles['Normal']))
                    
                    details = feature.get('details', [])
                    if details:
                        elements.append(Paragraph("Details:", styles['Normal']))
                        items = []
                        for detail in details:
                            items.append(ListItem(Paragraph(detail, styles['Normal'])))
                        elements.append(ListFlowable(items, bulletType='bullet', start='•'))
                        elements.append(Spacer(1, 6))
                
                # Add tech stack
                elements.append(Paragraph("Technology Stack", styles['Heading1']))
                tech_stack = documentation.get('tech_stack', [])
                for tech in tech_stack:
                    elements.append(Paragraph(tech.get('name', ''), styles['Heading2']))
                    elements.append(Paragraph(f"Category: {tech.get('category', '')}", styles['Normal']))
                    elements.append(Paragraph(tech.get('description', ''), styles['Normal']))
                    
                    benefits = tech.get('benefits', [])
                    if benefits:
                        elements.append(Paragraph("Benefits:", styles['Normal']))
                        items = []
                        for benefit in benefits:
                            items.append(ListItem(Paragraph(benefit, styles['Normal'])))
                        elements.append(ListFlowable(items, bulletType='bullet', start='•'))
                        elements.append(Spacer(1, 6))
                
                # Add footer
                elements.append(Spacer(1, 30))
                elements.append(Paragraph("Generated by DevBridge - AI-Powered Pre-Development Automation Platform", 
                                       ParagraphStyle(name='Footer', 
                                                  fontName='Helvetica', 
                                                  fontSize=8, 
                                                  textColor=colors.gray,
                                                  alignment=1)))
                
                # Build the PDF
                doc.build(elements)
                
                return output_path
            except Exception as e:
                print(f"Error exporting to simple PDF: {e}")
                import traceback
                traceback.print_exc()
                return None
    
    def export_to_pdf(self, documentation, output_path):
        """
        Export documentation to PDF.
        
        Args:
            documentation: The documentation object
            output_path: Path to save the PDF file
            
        Returns:
            Path to the generated PDF file
        """
        try:
            # Generate HTML
            html = self._generate_html(documentation)
            
            # Write HTML to temporary file
            with tempfile.NamedTemporaryFile(suffix='.html', delete=False) as temp_html:
                temp_html.write(html.encode('utf-8'))
                temp_html_path = temp_html.name
            
            # Convert HTML to PDF
            pdfkit.from_file(temp_html_path, output_path, options=self.pdf_options)
            
            # Clean up temporary file
            os.unlink(temp_html_path)
            
            return output_path
        except Exception as e:
            print(f"Error exporting to PDF: {e}")
            return None
    
    def export_to_docx(self, documentation, output_path):
        """
        Export documentation to DOCX.
        
        Args:
            documentation: The documentation object
            output_path: Path to save the DOCX file
            
        Returns:
            Path to the generated DOCX file
        """
        try:
            # Create document
            doc = Document()
            
            # Set document styles
            styles = doc.styles
            
            # Modify the Normal style
            style_normal = styles['Normal']
            font = style_normal.font
            font.name = 'Arial'
            font.size = Pt(11)
            
            # Modify Heading styles
            for level in range(1, 4):
                style_name = f'Heading {level}'
                if style_name in styles:
                    style = styles[style_name]
                    font = style.font
                    font.name = 'Arial'
                    font.bold = True
                    if level == 1:
                        font.size = Pt(18)
                        font.color.rgb = RGBColor(79, 70, 229)  # Primary color
                    elif level == 2:
                        font.size = Pt(16)
                        font.color.rgb = RGBColor(79, 70, 229)  # Primary color
                    else:
                        font.size = Pt(14)
                        font.color.rgb = RGBColor(107, 114, 128)  # Neutral color
            
            # Add title
            title = doc.add_heading(documentation.get('project_summary', {}).get('title', 'Project Documentation'), level=0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Add project summary
            doc.add_heading('Project Summary', level=1)
            doc.add_paragraph(documentation.get('project_summary', {}).get('description', ''))
            
            doc.add_heading('Objectives', level=2)
            objectives = doc.add_paragraph()
            for objective in documentation.get('project_summary', {}).get('objectives', []):
                objectives.add_run(f"• {objective}\n")
            
            doc.add_heading('Scope', level=2)
            doc.add_paragraph(documentation.get('project_summary', {}).get('scope', ''))
            
            # Add target audience
            doc.add_heading('Target Audience', level=1)
            doc.add_paragraph(f"Primary Audience: {documentation.get('target_audience', {}).get('primary_audience', '')}")
            
            secondary_audience = documentation.get('target_audience', {}).get('secondary_audience')
            if secondary_audience:
                doc.add_paragraph(f"Secondary Audience: {secondary_audience}")
            
            doc.add_heading('User Characteristics', level=2)
            characteristics = doc.add_paragraph()
            for characteristic in documentation.get('target_audience', {}).get('user_characteristics', []):
                characteristics.add_run(f"• {characteristic}\n")
            
            doc.add_heading('User Needs', level=2)
            needs = doc.add_paragraph()
            for need in documentation.get('target_audience', {}).get('user_needs', []):
                needs.add_run(f"• {need}\n")
            
            # Add features
            doc.add_heading('Features', level=1)
            for feature in documentation.get('features', []):
                doc.add_heading(feature.get('name', ''), level=2)
                doc.add_paragraph(feature.get('description', ''))
                doc.add_paragraph(f"Priority: {feature.get('priority', '')}")
                
                doc.add_heading('Details', level=3)
                details = doc.add_paragraph()
                for detail in feature.get('details', []):
                    details.add_run(f"• {detail}\n")
            
            # Add tech stack
            doc.add_heading('Technology Stack', level=1)
            for tech in documentation.get('tech_stack', []):
                doc.add_heading(tech.get('name', ''), level=2)
                doc.add_paragraph(f"Category: {tech.get('category', '')}")
                doc.add_paragraph(tech.get('description', ''))
                
                doc.add_heading('Benefits', level=3)
                benefits = doc.add_paragraph()
                for benefit in tech.get('benefits', []):
                    benefits.add_run(f"• {benefit}\n")
                
                alternatives = tech.get('alternatives')
                if alternatives and len(alternatives) > 0:
                    doc.add_heading('Alternatives', level=3)
                    alt_para = doc.add_paragraph()
                    for alternative in alternatives:
                        alt_para.add_run(f"• {alternative}\n")
            
            # Add content structure
            doc.add_heading('Content Structure', level=1)
            for section in documentation.get('content_structure', []):
                doc.add_heading(section.get('section_name', ''), level=2)
                doc.add_paragraph(section.get('description', ''))
                
                doc.add_heading('Content Elements', level=3)
                elements = doc.add_paragraph()
                for element in section.get('content_elements', []):
                    elements.add_run(f"• {element}\n")
                
                considerations = section.get('design_considerations')
                if considerations and len(considerations) > 0:
                    doc.add_heading('Design Considerations', level=3)
                    cons_para = doc.add_paragraph()
                    for consideration in considerations:
                        cons_para.add_run(f"• {consideration}\n")
            
            # Add implementation plan
            doc.add_heading('Implementation Plan', level=1)
            for step in sorted(documentation.get('implementation_plan', []), key=lambda x: x.get('step_number', 0)):
                doc.add_heading(f"Step {step.get('step_number', '')}: {step.get('title', '')}", level=2)
                doc.add_paragraph(step.get('description', ''))
                
                estimated_time = step.get('estimated_time')
                if estimated_time:
                    doc.add_paragraph(f"Estimated Time: {estimated_time}")
                
                dependencies = step.get('dependencies')
                if dependencies and len(dependencies) > 0:
                    doc.add_heading('Dependencies', level=3)
                    dep_para = doc.add_paragraph()
                    for dependency in dependencies:
                        dep_para.add_run(f"• Step {dependency}\n")
            
            # Add deployment strategy
            doc.add_heading('Deployment Strategy', level=1)
            doc.add_paragraph(f"Hosting Recommendation: {documentation.get('deployment_strategy', {}).get('hosting_recommendation', '')}")
            
            doc.add_heading('Deployment Steps', level=2)
            steps_para = doc.add_paragraph()
            for i, step in enumerate(documentation.get('deployment_strategy', {}).get('deployment_steps', []), 1):
                steps_para.add_run(f"{i}. {step}\n")
            
            doc.add_heading('Scaling Considerations', level=2)
            scaling_para = doc.add_paragraph()
            for consideration in documentation.get('deployment_strategy', {}).get('scaling_considerations', []):
                scaling_para.add_run(f"• {consideration}\n")
            
            maintenance_plan = documentation.get('deployment_strategy', {}).get('maintenance_plan')
            if maintenance_plan:
                doc.add_heading('Maintenance Plan', level=2)
                doc.add_paragraph(maintenance_plan)
            
            # Add footer
            section = doc.sections[0]
            footer = section.footer
            footer_para = footer.paragraphs[0]
            footer_para.text = "Generated by DevBridge - AI-Powered Pre-Development Automation Platform"
            footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Save document
            doc.save(output_path)
            
            return output_path
        except Exception as e:
            print(f"Error exporting to DOCX: {e}")
            return None

# Example usage
if __name__ == "__main__":
    # This is just for demonstration purposes
    with open('sample_documentation.json', 'r') as f:
        documentation = json.load(f)
    
    exporter = ExportEngine()
    pdf_path = exporter.export_to_pdf(documentation, 'documentation.pdf')
    docx_path = exporter.export_to_docx(documentation, 'documentation.docx')
    
    print(f"PDF exported to: {pdf_path}")
    print(f"DOCX exported to: {docx_path}")
